# source.pkr.hcl -- Defines the cloud-hypervisor source for direct kernel
# boot. Uses the Alpine Linux virt kernel and initramfs (generated by mkinitfs
# from the installed linux-virt package) with a proper Alpine sys installation
# on a partitioned raw disk image.
#
# File paths use path.root which resolves relative to this template directory.
# The assets directory is at examples/assets/ (one level up).

source "cloud-hypervisor" "kernel-boot" {
  # cloud-hypervisor binary path (default: resolved from PATH)
  ch_binary_path = var.ch_binary

  # CPU and memory configuration
  vcpus  = var.vcpus
  memory = var.memory

  # Direct kernel boot payload -- kernel + initramfs from linux-virt package
  # The initramfs is generated by mkinitfs and uses root=LABEL=alpine_root to
  # find and mount the root filesystem on /dev/vda1.
  kernel    = "${path.root}/../assets/alpine-vmlinuz"
  initramfs = "${path.root}/../assets/alpine-initramfs"
  cmdline   = "console=ttyS0,115200 root=LABEL=alpine_root rootfstype=ext4"

  # Root disk -- Alpine rootfs with SSH configured
  disk_images {
    path       = "${path.root}/../assets/alpine-rootfs.raw"
    readonly   = false
    image_type = "raw"
  }

  # Network interface -- bridged via TAP device
  network_interfaces {
    tap = var.tap_device
  }

  # No communicator (headless build) -- disk image is captured as artifact.
  # For SSH provisioning, configure networking (bridge + DHCP or static IP)
  # and switch communicator to "ssh".
  communicator = "none"

  # Serial and console are set to null since no provisioning is performed
  serial  = "null"
  console = "null"
}
